name: Tag on Merge

#该配置表示，当PR被合并到 main 分支并关闭时触发工作流。
on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    if: github.event.pull_request.merged == true #这部分确保只有在PR被合并时才执行该工作流。
    name: Tag on Merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #配置 Git 用户信息，确保能够正确推送标签。
      - name: Set up git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      #获取当前日期并存储到环境变量 DATE 中。
      - name: Get the current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      #获取最新的标签号，如果没有标签，则设置为1，否则将最新标签号+1。
      - name: Get the latest tag number
        id: tag_number
        run: |
          git fetch --tags
          latest_tag=$(git tag -l "${{ env.DATE }}-*" | sort -V | tail -n1)
          if [ -z "$latest_tag" ]; then
            echo "TAG_NUMBER=1" >> $GITHUB_ENV
          else
            latest_number=${latest_tag##*-}
            echo "TAG_NUMBER=$((latest_number + 1))" >> $GITHUB_ENV
          fi

      - name: Create new tag
        id: new_tag
        run: |
          new_tag="${{ env.DATE }}-${{ env.TAG_NUMBER }}"
          echo "Creating tag $new_tag"
          git tag $new_tag
          git push origin $new_tag
        env:
          DATE: ${{ env.DATE }}
          TAG_NUMBER: ${{ env.TAG_NUMBER }}
